= Getting Started With Spring REST Docs
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:

== News
=== GET
operation::news/get[snippets='curl-request,http-request,http-response,request-parameters,response-body,response-fields']
=== POST
operation::news/post[snippets='curl-request,http-request,http-response,request-body,request-fields']
=== PUT
operation::news/put[snippets='curl-request,http-request,http-response,request-body,request-fields']
=== DELETE
operation::news/delete[snippets='curl-request,http-request,http-response,request-parameters']
=== Exists
operation::news/getExists[snippets='curl-request,http-request,http-response,request-parameters,response-body,response-fields']

== Video
=== GET saved
operation::video/getSaved[snippets='curl-request,http-request,http-response,request-parameters,response-body,response-fields']
=== GET live
operation::video/getLive[snippets='curl-request,http-request,http-response,request-parameters,response-body,response-fields']
=== POST
operation::video/post[snippets='curl-request,http-request,http-response,request-body,request-fields']
=== PUT
operation::video/put[snippets='curl-request,http-request,http-response,request-body,request-fields']
=== DELETE
operation::video/delete[snippets='curl-request,http-request,http-response,request-parameters']
