version: "3.9"

services:
  app:
    container_name: covid19-api-prd
    image: covid19-api:latest
    env_file:
      - ${PWD}/docker/env/covid19-prd.env
    networks:
      - covid19-backend-prd
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  covid19-backend-prd:
    name: covid19-backend-prd
    driver: bridge
