version: "3.9"

services:
  app:
    container_name: covid19-api-dev
    image: openjdk:8-jdk-alpine
    env_file:
      - ${PWD}/docker/env/covid19-dev.env
    volumes:
      - ${PWD}/build/libs:/app/libs
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - covid19-backend-dev
    expose:
      - "8080"
    entrypoint: ["java","-jar","/app/libs/dev-covid19-api-0.0.1-SNAPSHOT.jar"]

  db:
    image: postgres:13.5
    container_name: covid19-db-dev
    environment:
      POSTGRES_PASSWORD: postgres_dev
    networks:
      - covid19-backend-dev
    volumes:
      - ${PWD}/schema:/docker-entrypoint-initdb.d:ro

networks:
  covid19-backend-dev:
    name: covid19-backend-dev
    driver: bridge
