version: "3.9"

services:
  app:
    container_name: covid19-api-prd
    image: openjdk:8-jdk-alpine
    env_file:
      - ${PWD}/docker/env/covid19-prd.env
    volumes:
      - ${PWD}/build/libs:/app/libs
    networks:
      - covid19-backend-prd
    expose:
      - "8080"
    entrypoint: ["java","-jar","/app/libs/dev-covid19-api-0.0.1-SNAPSHOT.jar"]

networks:
  covid19-backend-prd:
    name: covid19-backend-prd
    driver: bridge
